<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 5: EDA Practice</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#task-1-read-in-the-data-and-modify" id="toc-task-1-read-in-the-data-and-modify" class="nav-link active" data-scroll-target="#task-1-read-in-the-data-and-modify">Task 1: Read in the Data and Modify</a>
  <ul class="collapse">
  <li><a href="#reading-in-with-base-r" id="toc-reading-in-with-base-r" class="nav-link" data-scroll-target="#reading-in-with-base-r">Reading in with Base R</a></li>
  <li><a href="#reading-in-with-tidyverse" id="toc-reading-in-with-tidyverse" class="nav-link" data-scroll-target="#reading-in-with-tidyverse">Reading in with Tidyverse</a>
  <ul class="collapse">
  <li><a href="#tidyverse---join-on-additional-columns" id="toc-tidyverse---join-on-additional-columns" class="nav-link" data-scroll-target="#tidyverse---join-on-additional-columns">Tidyverse - join on additional columns</a></li>
  </ul></li>
  <li><a href="#categorical-variables-convert-to-factor" id="toc-categorical-variables-convert-to-factor" class="nav-link" data-scroll-target="#categorical-variables-convert-to-factor">Categorical variables: convert to factor</a></li>
  </ul></li>
  <li><a href="#task-2-summarize-the-data-very-basic-eda" id="toc-task-2-summarize-the-data-very-basic-eda" class="nav-link" data-scroll-target="#task-2-summarize-the-data-very-basic-eda">Task 2: Summarize the Data (Very Basic EDA)</a>
  <ul class="collapse">
  <li><a href="#how-data-is-stored" id="toc-how-data-is-stored" class="nav-link" data-scroll-target="#how-data-is-stored">How Data is Stored</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">Missing Values</a></li>
  <li><a href="#categorical-variables" id="toc-categorical-variables" class="nav-link" data-scroll-target="#categorical-variables">Categorical Variables</a>
  <ul class="collapse">
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables">Contingency Tables</a></li>
  <li><a href="#conditional-contingency-tables" id="toc-conditional-contingency-tables" class="nav-link" data-scroll-target="#conditional-contingency-tables">Conditional Contingency Tables</a></li>
  <li><a href="#bar-graphs" id="toc-bar-graphs" class="nav-link" data-scroll-target="#bar-graphs">Bar graphs</a></li>
  </ul></li>
  <li><a href="#numeric-variables" id="toc-numeric-variables" class="nav-link" data-scroll-target="#numeric-variables">Numeric Variables</a>
  <ul class="collapse">
  <li><a href="#measures-of-center-and-spread-no-grouping" id="toc-measures-of-center-and-spread-no-grouping" class="nav-link" data-scroll-target="#measures-of-center-and-spread-no-grouping">Measures of center and spread (no grouping)</a></li>
  <li><a href="#measures-of-center-and-spread-grouping-with-single-variable" id="toc-measures-of-center-and-spread-grouping-with-single-variable" class="nav-link" data-scroll-target="#measures-of-center-and-spread-grouping-with-single-variable">Measures of center and spread (grouping with single variable)</a></li>
  <li><a href="#measures-of-center-and-spread-grouping-with-two-variables" id="toc-measures-of-center-and-spread-grouping-with-two-variables" class="nav-link" data-scroll-target="#measures-of-center-and-spread-grouping-with-two-variables">Measures of center and spread (grouping with two variables)</a></li>
  <li><a href="#correlation-matrix-for-all-numeric-variables" id="toc-correlation-matrix-for-all-numeric-variables" class="nav-link" data-scroll-target="#correlation-matrix-for-all-numeric-variables">Correlation matrix for all numeric variables</a></li>
  <li><a href="#histogram-kernel-density-plot-and-boxplot" id="toc-histogram-kernel-density-plot-and-boxplot" class="nav-link" data-scroll-target="#histogram-kernel-density-plot-and-boxplot">Histogram, kernel density plot, and boxplot</a></li>
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots">Scatterplots</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 5: EDA Practice</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Libraries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<section id="task-1-read-in-the-data-and-modify" class="level1">
<h1>Task 1: Read in the Data and Modify</h1>
<section id="reading-in-with-base-r" class="level2">
<h2 class="anchored" data-anchor-id="reading-in-with-base-r">Reading in with Base R</h2>
<p>Read in csv data, using a modification of the R code in the zipped file download.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"student-mat.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"student-por.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> <span class="fu">merge</span>(d1,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            d2,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">by=</span><span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(d3)) <span class="co"># 382 students</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 382</code></pre>
</div>
</div>
</section>
<section id="reading-in-with-tidyverse" class="level2">
<h2 class="anchored" data-anchor-id="reading-in-with-tidyverse">Reading in with Tidyverse</h2>
<p>Read in and combine datasets using tidyverse (semicolon delimiter).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>student_mat <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">"student-mat.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 395 Columns: 33
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (17): school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardi...
dbl (16): age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>student_por <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(<span class="st">"student-por.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
Rows: 649 Columns: 33── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (17): school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardi...
dbl (16): age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime...
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>student_all <span class="ot">&lt;-</span> student_mat <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(student_por, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,<span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(student_mat, student_por, by = c("school", "sex", : Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 79 of `x` matches multiple rows in `y`.
ℹ Row 79 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
</div>
<p>There are at least a couple of issues with the resulting data set.</p>
<ul>
<li>The warning above shows that the criteria on which the data sets were joined do not have a unique set of values for each observation, so this duplicates observations (i.e.&nbsp;a many-to-many match).</li>
<li>Additionally, after inner joining there are only 382 observations, whereas both the math and portuguese datasets had more than this–395 and 649, respectively. Therefore, the final dataset has dropped observations from both datasets since they didn’t have a match in the other one.</li>
<li>Because this only joined on a handful of columns, and the initial data sets both have the same variables, there are a lot of columns with potentially duplicated information.</li>
</ul>
<section id="tidyverse---join-on-additional-columns" class="level3">
<h3 class="anchored" data-anchor-id="tidyverse---join-on-additional-columns">Tidyverse - join on additional columns</h3>
<p>Still use tidyverse, but join on all variables in each data set, except for G1, G2, G3, paid, and absences.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a set of columns to join on</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>join_columns <span class="ot">&lt;-</span> <span class="fu">names</span>(student_mat) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setdiff</span>(<span class="fu">c</span>(<span class="st">"G1"</span>, <span class="st">"G2"</span>, <span class="st">"G3"</span>, <span class="st">"paid"</span>, <span class="st">"absences"</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># join the data sets</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>student_combined <span class="ot">&lt;-</span> student_mat <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(student_por, <span class="at">by =</span> join_columns, <span class="at">suffix =</span> <span class="fu">c</span>(<span class="st">"_mat"</span>, <span class="st">"_por"</span>))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(student_combined))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 320</code></pre>
</div>
</div>
<p>No warnings this time, but there are only 320 rows, so I know it doesn’t have all observations from either data set since some didn’t match observations in the other data set.</p>
</section>
</section>
<section id="categorical-variables-convert-to-factor" class="level2">
<h2 class="anchored" data-anchor-id="categorical-variables-convert-to-factor">Categorical variables: convert to factor</h2>
<p>Convert 4 categorical variables to factors using mutate</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># math data set</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>student_mat <span class="ot">&lt;-</span> student_mat <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">studytimeF =</span> <span class="fu">factor</span>(studytime,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"&lt;2 hours"</span>, <span class="st">"2 to 5 hours"</span>, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"5 to 10 hours"</span>,<span class="st">"&gt;10 hours"</span>)),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">schoolsupF =</span> <span class="fu">as.factor</span>(schoolsup),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">famsupF =</span> <span class="fu">as.factor</span>(famsup),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">addressF =</span> <span class="fu">factor</span>(address, </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"U"</span>, <span class="st">"R"</span>), </span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Urban"</span>, <span class="st">"Rural"</span>))</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co"># portuguese data set</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>student_por <span class="ot">&lt;-</span> student_por <span class="sc">|&gt;</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">studytimeF =</span> <span class="fu">factor</span>(studytime,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>),</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"&lt;2 hours"</span>, <span class="st">"2 to 5 hours"</span>, </span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"5 to 10 hours"</span>,<span class="st">"&gt;10 hours"</span>)),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">schoolsupF =</span> <span class="fu">as.factor</span>(schoolsup),</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">famsupF =</span> <span class="fu">as.factor</span>(famsup),</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">addressF =</span> <span class="fu">factor</span>(address, </span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"U"</span>, <span class="st">"R"</span>), </span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Urban"</span>, <span class="st">"Rural"</span>))</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="co"># combined data set</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>student_combined <span class="ot">&lt;-</span> student_combined <span class="sc">|&gt;</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">studytimeF =</span> <span class="fu">factor</span>(studytime,</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>),</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>                             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"&lt;2 hours"</span>, <span class="st">"2 to 5 hours"</span>, </span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"5 to 10 hours"</span>,<span class="st">"&gt;10 hours"</span>)),</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>         <span class="at">schoolsupF =</span> <span class="fu">as.factor</span>(schoolsup),</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>         <span class="at">famsupF =</span> <span class="fu">as.factor</span>(famsup),</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>         <span class="at">addressF =</span> <span class="fu">factor</span>(address, </span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>                           <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"U"</span>, <span class="st">"R"</span>), </span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Urban"</span>, <span class="st">"Rural"</span>))</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="task-2-summarize-the-data-very-basic-eda" class="level1">
<h1>Task 2: Summarize the Data (Very Basic EDA)</h1>
<section id="how-data-is-stored" class="level2">
<h2 class="anchored" data-anchor-id="how-data-is-stored">How Data is Stored</h2>
<p><em>Data validation: checking basic summary statistics</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(student_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             vars   n  mean   sd median trimmed  mad min max range  skew
school*         1 320  1.10 0.30    1.0    1.00 0.00   1   2     1  2.60
sex*            2 320  1.46 0.50    1.0    1.45 0.00   1   2     1  0.17
age             3 320 16.52 1.14   16.0   16.49 1.48  15  22     7  0.43
address*        4 320  1.79 0.41    2.0    1.86 0.00   1   2     1 -1.42
famsize*        5 320  1.28 0.45    1.0    1.23 0.00   1   2     1  0.97
Pstatus*        6 320  1.90 0.30    2.0    2.00 0.00   1   2     1 -2.71
Medu            7 320  2.87 1.07    3.0    2.97 1.48   0   4     4 -0.43
Fedu            8 320  2.62 1.09    3.0    2.66 1.48   0   4     4 -0.16
Mjob*           9 320  3.21 1.24    3.0    3.26 1.48   1   5     4 -0.29
Fjob*          10 320  3.31 0.86    3.0    3.32 0.00   1   5     4 -0.25
reason*        11 320  2.26 1.21    2.0    2.20 1.48   1   4     3  0.40
guardian*      12 320  1.80 0.47    2.0    1.84 0.00   1   3     2 -0.60
traveltime     13 320  1.43 0.69    1.0    1.29 0.00   1   4     3  1.65
studytime      14 320  2.08 0.87    2.0    2.00 1.48   1   4     3  0.59
failures       15 320  0.08 0.39    0.0    0.00 0.00   0   3     3  5.92
schoolsup*     16 320  1.13 0.34    1.0    1.04 0.00   1   2     1  2.13
famsup*        17 320  1.63 0.48    2.0    1.67 0.00   1   2     1 -0.56
paid_mat*      18 320  1.50 0.50    1.5    1.50 0.74   1   2     1  0.00
activities*    19 320  1.53 0.50    2.0    1.54 0.00   1   2     1 -0.12
nursery*       20 320  1.82 0.39    2.0    1.89 0.00   1   2     1 -1.62
higher*        21 320  1.98 0.15    2.0    2.00 0.00   1   2     1 -6.51
internet*      22 320  1.85 0.36    2.0    1.94 0.00   1   2     1 -1.95
romantic*      23 320  1.31 0.46    1.0    1.26 0.00   1   2     1  0.82
famrel         24 320  3.99 0.89    4.0    4.08 1.48   1   5     4 -0.98
freetime       25 320  3.20 0.97    3.0    3.20 1.48   1   5     4 -0.14
goout          26 320  3.07 1.10    3.0    3.04 1.48   1   5     4  0.16
Dalc           27 320  1.44 0.88    1.0    1.21 0.00   1   5     4  2.34
Walc           28 320  2.22 1.26    2.0    2.08 1.48   1   5     4  0.68
health         29 320  3.52 1.42    4.0    3.65 1.48   1   5     4 -0.49
absences_mat   30 320  5.41 7.84    4.0    4.00 5.93   0  75    75  4.25
G1_mat         31 320 11.29 3.20   11.0   11.19 2.97   5  19    14  0.27
G2_mat         32 320 11.18 3.67   11.0   11.29 2.97   0  19    19 -0.45
G3_mat         33 320 11.04 4.30   11.0   11.38 4.45   0  20    20 -0.76
paid_por*      34 320  1.06 0.24    1.0    1.00 0.00   1   2     1  3.60
absences_por   35 320  3.25 4.56    2.0    2.33 2.97   0  32    32  2.53
G1_por         36 320 12.39 2.56   12.0   12.41 2.97   0  19    19 -0.31
G2_por         37 320 12.57 2.42   12.0   12.52 2.97   5  19    14  0.20
G3_por         38 320 12.88 2.89   13.0   12.97 2.97   0  19    19 -1.13
studytimeF*    39 320  2.08 0.87    2.0    2.00 1.48   1   4     3  0.59
schoolsupF*    40 320  1.13 0.34    1.0    1.04 0.00   1   2     1  2.13
famsupF*       41 320  1.63 0.48    2.0    1.67 0.00   1   2     1 -0.56
addressF*      42 320  1.21 0.41    1.0    1.14 0.00   1   2     1  1.42
             kurtosis   se
school*          4.76 0.02
sex*            -1.98 0.03
age              0.35 0.06
address*         0.02 0.02
famsize*        -1.07 0.03
Pstatus*         5.38 0.02
Medu            -1.03 0.06
Fedu            -1.16 0.06
Mjob*           -0.71 0.07
Fjob*            0.90 0.05
reason*         -1.41 0.07
guardian*        0.21 0.03
traveltime       2.46 0.04
studytime       -0.20 0.05
failures        38.64 0.02
schoolsup*       2.56 0.02
famsup*         -1.70 0.03
paid_mat*       -2.01 0.03
activities*     -1.99 0.03
nursery*         0.63 0.02
higher*         40.46 0.01
internet*        1.81 0.02
romantic*       -1.33 0.03
famrel           1.21 0.05
freetime        -0.27 0.05
goout           -0.73 0.06
Dalc             5.32 0.05
Walc            -0.69 0.07
health          -1.07 0.08
absences_mat    27.83 0.44
G1_mat          -0.70 0.18
G2_mat           0.62 0.21
G3_mat           0.75 0.24
paid_por*       10.98 0.01
absences_por     9.37 0.25
G1_por           1.08 0.14
G2_por          -0.19 0.14
G3_por           4.18 0.16
studytimeF*     -0.20 0.05
schoolsupF*      2.56 0.02
famsupF*        -1.70 0.03
addressF*        0.02 0.02</code></pre>
</div>
</div>
<ul>
<li>I compared the above values with the documentation provided on the <a href="https://archive.ics.uci.edu/dataset/320/student+performance">data download website</a>.</li>
<li>Main focus was ensuring the min and max values aligned with what the documentation says they should be, and for the most part they look as expected.
<ul>
<li>For numeric columns, I checked that the min and max were the same as the range stated for the column in the documentation</li>
<li>For categorical variables (marked with asterisks in the above table), the min and max “values” really just reflect how many unique values there are in the column, so I just made sure the max was the same as the number of possible values for that column</li>
</ul></li>
<li>Documentation states that the range for the failures column is 1-4. However, in the combined data the min is 0 and the max is 3. I checked the counts for each value in the combined and the original data sets (see below), since I wondered if there were some in math or portuguese data sets that were lost after the inner join. However, there were no 4+ failures in any of them.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(failures) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  failures count
     &lt;dbl&gt; &lt;int&gt;
1        0   302
2        1    14
3        3     4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>student_mat <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(failures) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  failures count
     &lt;dbl&gt; &lt;int&gt;
1        0   312
2        1    50
3        2    17
4        3    16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>student_por <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(failures) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  failures count
     &lt;dbl&gt; &lt;int&gt;
1        0   549
2        1    70
3        2    16
4        3    14</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(student_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [320 × 42] (S3: tbl_df/tbl/data.frame)
 $ school      : chr [1:320] "GP" "GP" "GP" "GP" ...
 $ sex         : chr [1:320] "F" "F" "F" "F" ...
 $ age         : num [1:320] 18 17 15 16 16 16 17 15 15 15 ...
 $ address     : chr [1:320] "U" "U" "U" "U" ...
 $ famsize     : chr [1:320] "GT3" "GT3" "GT3" "GT3" ...
 $ Pstatus     : chr [1:320] "A" "T" "T" "T" ...
 $ Medu        : num [1:320] 4 1 4 3 4 2 4 3 3 4 ...
 $ Fedu        : num [1:320] 4 1 2 3 3 2 4 2 4 4 ...
 $ Mjob        : chr [1:320] "at_home" "at_home" "health" "other" ...
 $ Fjob        : chr [1:320] "teacher" "other" "services" "other" ...
 $ reason      : chr [1:320] "course" "course" "home" "home" ...
 $ guardian    : chr [1:320] "mother" "father" "mother" "father" ...
 $ traveltime  : num [1:320] 2 1 1 1 1 1 2 1 1 1 ...
 $ studytime   : num [1:320] 2 2 3 2 2 2 2 2 2 2 ...
 $ failures    : num [1:320] 0 0 0 0 0 0 0 0 0 0 ...
 $ schoolsup   : chr [1:320] "yes" "no" "no" "no" ...
 $ famsup      : chr [1:320] "no" "yes" "yes" "yes" ...
 $ paid_mat    : chr [1:320] "no" "no" "yes" "yes" ...
 $ activities  : chr [1:320] "no" "no" "yes" "no" ...
 $ nursery     : chr [1:320] "yes" "no" "yes" "yes" ...
 $ higher      : chr [1:320] "yes" "yes" "yes" "yes" ...
 $ internet    : chr [1:320] "no" "yes" "yes" "no" ...
 $ romantic    : chr [1:320] "no" "no" "yes" "no" ...
 $ famrel      : num [1:320] 4 5 3 4 5 4 4 4 5 3 ...
 $ freetime    : num [1:320] 3 3 2 3 4 4 1 2 5 3 ...
 $ goout       : num [1:320] 4 3 2 2 2 4 4 2 1 3 ...
 $ Dalc        : num [1:320] 1 1 1 1 1 1 1 1 1 1 ...
 $ Walc        : num [1:320] 1 1 1 2 2 1 1 1 1 2 ...
 $ health      : num [1:320] 3 3 5 5 5 3 1 1 5 2 ...
 $ absences_mat: num [1:320] 6 4 2 4 10 0 6 0 0 0 ...
 $ G1_mat      : num [1:320] 5 5 15 6 15 12 6 16 14 10 ...
 $ G2_mat      : num [1:320] 6 5 14 10 15 12 5 18 15 8 ...
 $ G3_mat      : num [1:320] 6 6 15 10 15 11 6 19 15 9 ...
 $ paid_por    : chr [1:320] "no" "no" "no" "no" ...
 $ absences_por: num [1:320] 4 2 0 0 6 0 2 0 0 2 ...
 $ G1_por      : num [1:320] 0 9 14 11 12 13 10 15 12 14 ...
 $ G2_por      : num [1:320] 11 11 14 13 12 12 13 16 12 14 ...
 $ G3_por      : num [1:320] 11 11 14 13 13 13 13 17 13 14 ...
 $ studytimeF  : Factor w/ 4 levels "&lt;2 hours","2 to 5 hours",..: 2 2 3 2 2 2 2 2 2 2 ...
 $ schoolsupF  : Factor w/ 2 levels "no","yes": 2 1 1 1 1 1 2 1 1 1 ...
 $ famsupF     : Factor w/ 2 levels "no","yes": 1 2 2 2 2 1 2 2 2 2 ...
 $ addressF    : Factor w/ 2 levels "Urban","Rural": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p><em>Do the data types make sense?</em></p>
<ul>
<li>There are a lot of variables in this data set that use numbers to code for values that are non-numeric. So even though R read them in as numeric, it is not meaningful to do mathematical operations on them, so they will be changed to character.
<ul>
<li>Integer representations of education level (Medu, Fedu)</li>
<li>Time ranges (traveltime, studytime)</li>
<li>n &lt; 4 is an actual count, but n = 4 is a catchall value for n &gt;= 4 (failures). Mathematical operations can be done if filtered on n &lt; 4, but it might be best to change it to character since just excluding a high number of failures might not have a lot of analytic value.</li>
<li>ranked measures on a scale of 1 to 5 (famrel, freetime, goout, Dalc, Walc, health)</li>
</ul></li>
<li>There are 10 variables that are just yes/no fields, so they are binary. Technically they can be stored as boolean, but they’ll be left as yes/no just because those values look nicer in tables and there’s not a chance of accidentally coercing them to numeric like there is with boolean.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="ot">&lt;-</span> student_combined <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Medu =</span> <span class="fu">as.character</span>(Medu),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Fedu =</span> <span class="fu">as.character</span>(Fedu),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">traveltime =</span> <span class="fu">as.character</span>(traveltime),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">studytime =</span> <span class="fu">as.character</span>(studytime),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">failures =</span> <span class="fu">as.character</span>(failures), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">famrel =</span> <span class="fu">as.character</span>(famrel),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">freetime =</span> <span class="fu">as.character</span>(freetime),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">goout =</span> <span class="fu">as.character</span>(goout),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Dalc =</span> <span class="fu">as.character</span>(Dalc),</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Walc =</span> <span class="fu">as.character</span>(Walc),</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">health =</span> <span class="fu">as.character</span>(health)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">Missing Values</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>sum_na <span class="ot">&lt;-</span> <span class="cf">function</span>(column) {</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(column))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>na_counts <span class="ot">&lt;-</span> student_combined <span class="sc">|&gt;</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), sum_na)) <span class="sc">|&gt;</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"count"</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>na_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 42 × 2
   Variable count
   &lt;chr&gt;    &lt;int&gt;
 1 school       0
 2 sex          0
 3 age          0
 4 address      0
 5 famsize      0
 6 Pstatus      0
 7 Medu         0
 8 Fedu         0
 9 Mjob         0
10 Fjob         0
# ℹ 32 more rows</code></pre>
</div>
</div>
<p>No missing values are found, which is consistent with the documentation for the data set.</p>
</section>
<section id="categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="categorical-variables">Categorical Variables</h2>
<section id="contingency-tables" class="level3">
<h3 class="anchored" data-anchor-id="contingency-tables">Contingency Tables</h3>
<p>Combined data set, using table()</p>
<ol class="example" type="1">
<li>One-way contingency table</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(student_combined<span class="sc">$</span>addressF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Urban Rural 
  253    67 </code></pre>
</div>
</div>
<p>There are 253 students in this study who live at an urban address.</p>
<ol start="2" class="example" type="1">
<li>Two-way contingency table</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(student_combined<span class="sc">$</span>addressF, student_combined<span class="sc">$</span>studytimeF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Urban       59          132            42        20
  Rural       22           25            14         6</code></pre>
</div>
</div>
<p>There are only 6 rural students who spend more than 10 hours studying.</p>
<ol start="3" class="example" type="1">
<li>Three-way contingency table</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(student_combined<span class="sc">$</span>studytimeF,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>      student_combined<span class="sc">$</span>famsupF,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>      student_combined<span class="sc">$</span>addressF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = Urban

               
                no yes
  &lt;2 hours      31  28
  2 to 5 hours  43  89
  5 to 10 hours 12  30
  &gt;10 hours      6  14

, ,  = Rural

               
                no yes
  &lt;2 hours       9  13
  2 to 5 hours   9  16
  5 to 10 hours  6   8
  &gt;10 hours      1   5</code></pre>
</div>
</div>
<p>The number of urban students that have family support and also devote 2 to 5 hours to studying is 89.</p>
</section>
<section id="conditional-contingency-tables" class="level3">
<h3 class="anchored" data-anchor-id="conditional-contingency-tables">Conditional Contingency Tables</h3>
<ol type="1">
<li>Conditional two-way table in base R</li>
</ol>
<ul>
<li>Subset data, then create table with table()</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>data_subset <span class="ot">&lt;-</span> student_combined <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(schoolsupF <span class="sc">==</span> <span class="st">"no"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_subset<span class="sc">$</span>famsupF, data_subset<span class="sc">$</span>studytimeF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  no        39           43            17         6
  yes       32           90            34        16</code></pre>
</div>
</div>
<p>Out of the subset of kids without school support, the largest relative frequency category for kids with and without family support is 2 to 5 hours of studying.</p>
<ol start="2" type="1">
<li>Conditional two-way table in base R</li>
</ol>
<ul>
<li>Create a three-way table with table(), then subset it</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>data_table <span class="ot">&lt;-</span> <span class="fu">table</span>(student_combined<span class="sc">$</span>famsupF,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                    student_combined<span class="sc">$</span>studytimeF,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                    student_combined<span class="sc">$</span>schoolsupF)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>data_table[ , , <span class="st">"no"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  no        39           43            17         6
  yes       32           90            34        16</code></pre>
</div>
</div>
<p>As shown above, this alternate way of producing a conditional contingency table has produced an equivalent result to the prior method.</p>
<ol start="3" type="1">
<li>Two-way contingency table using dplyr</li>
</ol>
<ul>
<li>Utilize group_by(), summarize(), pivot_wider()</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(famsupF, studytimeF) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> studytimeF, <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'famsupF'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
# Groups:   famsupF [2]
  famsupF `&lt;2 hours` `2 to 5 hours` `5 to 10 hours` `&gt;10 hours`
  &lt;fct&gt;        &lt;int&gt;          &lt;int&gt;           &lt;int&gt;       &lt;int&gt;
1 no              40             52              18           7
2 yes             41            105              38          19</code></pre>
</div>
</div>
<p>Interesting that nearly the same number of students in both groups spend &lt;2 hours studying, even though the group with family support is a lot larger.</p>
</section>
<section id="bar-graphs" class="level3">
<h3 class="anchored" data-anchor-id="bar-graphs">Bar graphs</h3>
<ol type="1">
<li>Stacked bar graph</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined, <span class="fu">aes</span>(<span class="at">x =</span> famsupF, <span class="at">fill =</span> studytimeF))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Study time with and without Family Support"</span>) <span class="sc">+</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Family Support"</span>, <span class="at">y =</span> <span class="st">"Number of Students"</span>) <span class="sc">+</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Students are more likely than not to have family support. Most kids in both groups put in between 0 and 5 hours of studying. When they do put in up to 5 hours of studying, the kids with family support are more likely to devote 2-5 hours of studying, rather than &lt;2 hours.</p>
<ol start="2" type="1">
<li>Side-by-side bar graph</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined, <span class="fu">aes</span>(<span class="at">x =</span> famsupF, <span class="at">fill =</span> studytimeF))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Study time with and without Family Support"</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Family Support"</span>, <span class="at">y =</span> <span class="st">"Number of Students"</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The side-by-side bars make it easier to see that almost the same number of students in both groups are in the &lt;2 hours category. With or without family support, not many students are putting in more than 10 hours, but a significantly higher proportion of kids with family support allocate 5 to 10 hours to studying compared to the non-supported kids.</p>
</section>
</section>
<section id="numeric-variables" class="level2">
<h2 class="anchored" data-anchor-id="numeric-variables">Numeric Variables</h2>
<section id="measures-of-center-and-spread-no-grouping" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-center-and-spread-no-grouping">Measures of center and spread (no grouping)</h3>
<ul>
<li>Measures of center and spread, 3 numeric variables, full data</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age, absences_mat, G3_mat),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean, <span class="st">"median"</span> <span class="ot">=</span> median, <span class="st">"IQR"</span> <span class="ot">=</span> IQR, <span class="st">"sd"</span> <span class="ot">=</span> sd),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Statistic"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   Statistic           Value
   &lt;chr&gt;               &lt;dbl&gt;
 1 mean_age            16.5 
 2 median_age          16   
 3 IQR_age              1   
 4 sd_age               1.14
 5 mean_absences_mat    5.41
 6 median_absences_mat  4   
 7 IQR_absences_mat     7.25
 8 sd_absences_mat      7.84
 9 mean_G3_mat         11.0 
10 median_G3_mat       11   
11 IQR_G3_mat           5   
12 sd_G3_mat            4.30</code></pre>
</div>
</div>
<p>Mean and median G3 math scores are really close together, so the distribution of scores is probably not very skewed.</p>
<ul>
<li>Measures of center and spread, 3 numeric variables with a subset of data</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(addressF <span class="sc">==</span> <span class="st">"Rural"</span>) <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age, absences_mat, G3_mat),</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean, <span class="st">"median"</span> <span class="ot">=</span> median, <span class="st">"IQR"</span> <span class="ot">=</span> IQR, <span class="st">"sd"</span> <span class="ot">=</span> sd),</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Statistic"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   Statistic           Value
   &lt;chr&gt;               &lt;dbl&gt;
 1 mean_age            17.0 
 2 median_age          17   
 3 IQR_age              2   
 4 sd_age               1.12
 5 mean_absences_mat    6.12
 6 median_absences_mat  4   
 7 IQR_absences_mat     6   
 8 sd_absences_mat      9.80
 9 mean_G3_mat          9.90
10 median_G3_mat       10   
11 IQR_G3_mat           4   
12 sd_G3_mat            4.59</code></pre>
</div>
</div>
<p>Median age for rural students is 17, and the IQR is only 2 years, so the middle 50% of students are between the ages of 16 and 18.</p>
</section>
<section id="measures-of-center-and-spread-grouping-with-single-variable" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-center-and-spread-grouping-with-single-variable">Measures of center and spread (grouping with single variable)</h3>
<ul>
<li>Measure of center</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(addressF) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age, absences_mat, G3_mat),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean, <span class="st">"median"</span> <span class="ot">=</span> median),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  addressF mean_age median_age mean_absences_mat median_absences_mat mean_G3_mat
  &lt;fct&gt;       &lt;dbl&gt;      &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;       &lt;dbl&gt;
1 Urban        16.4         16              5.23                   4       11.3 
2 Rural        17.0         17              6.12                   4        9.90
# ℹ 1 more variable: median_G3_mat &lt;dbl&gt;</code></pre>
</div>
</div>
<p>On average, rural students have roughly 1 more absence than urban students.</p>
<ul>
<li>Measure of spread</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(addressF) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age, absences_mat, G3_mat),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"IQR"</span> <span class="ot">=</span> IQR, <span class="st">"sd"</span> <span class="ot">=</span> sd),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  addressF IQR_age sd_age IQR_absences_mat sd_absences_mat IQR_G3_mat sd_G3_mat
  &lt;fct&gt;      &lt;dbl&gt;  &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 Urban          1   1.12                6            7.24          5      4.18
2 Rural          2   1.12                6            9.80          4      4.59</code></pre>
</div>
</div>
<p>Urban students have a larger range of G3 math scores in their middle 50% than the rural students do.</p>
</section>
<section id="measures-of-center-and-spread-grouping-with-two-variables" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-center-and-spread-grouping-with-two-variables">Measures of center and spread (grouping with two variables)</h3>
<ul>
<li>Measures of center</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(addressF, famsupF) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age, absences_mat, G3_mat),</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"mean"</span> <span class="ot">=</span> mean, <span class="st">"median"</span> <span class="ot">=</span> median),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'addressF'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 8
# Groups:   addressF [2]
  addressF famsupF mean_age median_age mean_absences_mat median_absences_mat
  &lt;fct&gt;    &lt;fct&gt;      &lt;dbl&gt;      &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;
1 Urban    no          16.5         16              4.97                   4
2 Urban    yes         16.4         16              5.37                   2
3 Rural    no          17.4         18              6.4                    2
4 Rural    yes         16.7         17              5.95                   6
# ℹ 2 more variables: mean_G3_mat &lt;dbl&gt;, median_G3_mat &lt;dbl&gt;</code></pre>
</div>
</div>
<p>It’s interesting that the rural kids with family support have fewer absences than the rural kids without family support, but in the urban group, that relationship is reversed.</p>
<ul>
<li>Measures of spread</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(addressF, famsupF) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age, absences_mat, G3_mat),</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="st">"IQR"</span> <span class="ot">=</span> IQR, <span class="st">"sd"</span> <span class="ot">=</span> sd),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'addressF'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 8
# Groups:   addressF [2]
  addressF famsupF IQR_age sd_age IQR_absences_mat sd_absences_mat IQR_G3_mat
  &lt;fct&gt;    &lt;fct&gt;     &lt;dbl&gt;  &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;
1 Urban    no            1   1.15             7.25            5.62       5   
2 Urban    yes           2   1.10             6               8.03       5   
3 Rural    no            1   1.08             8              14.9        5   
4 Rural    yes           1   1.09             6               4.92       4.75
# ℹ 1 more variable: sd_G3_mat &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Rural student absences without family support have a much higher standard deviation than the other categories, so there is a lot more variation in the number of absences compared to the other groups.</p>
</section>
<section id="correlation-matrix-for-all-numeric-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlation-matrix-for-all-numeric-variables">Correlation matrix for all numeric variables</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>student_combined <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">|&gt;</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">|&gt;</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               age absences_mat G1_mat G2_mat G3_mat absences_por G1_por G2_por
age           1.00         0.14  -0.11  -0.19  -0.21         0.05  -0.05   0.03
absences_mat  0.14         1.00  -0.07  -0.08  -0.03         0.56  -0.09  -0.15
G1_mat       -0.11        -0.07   1.00   0.87   0.82        -0.09   0.59   0.60
G2_mat       -0.19        -0.08   0.87   1.00   0.91        -0.13   0.54   0.57
G3_mat       -0.21        -0.03   0.82   0.91   1.00        -0.12   0.52   0.55
absences_por  0.05         0.56  -0.09  -0.13  -0.12         1.00  -0.10  -0.12
G1_por       -0.05        -0.09   0.59   0.54   0.52        -0.10   1.00   0.88
G2_por        0.03        -0.15   0.60   0.57   0.55        -0.12   0.88   1.00
G3_por       -0.01        -0.14   0.54   0.50   0.48        -0.07   0.83   0.89
             G3_por
age           -0.01
absences_mat  -0.14
G1_mat         0.54
G2_mat         0.50
G3_mat         0.48
absences_por  -0.07
G1_por         0.83
G2_por         0.89
G3_por         1.00</code></pre>
</div>
</div>
<p>It’s interesting that G1, G2, and G3 scores within the same subject are highly correlated with each other, while the scores between subjects still correlate, just not as strongly. Students may apply the same set of study skills across subjects, so that their scores would be related. It makes intuitive sense that the correlation of scores in different subjects would be less strong, since math and portuguese require differing sets of skills to perform well. There seems to be no discernible linear relationship among the other numeric variables.</p>
</section>
<section id="histogram-kernel-density-plot-and-boxplot" class="level3">
<h3 class="anchored" data-anchor-id="histogram-kernel-density-plot-and-boxplot">Histogram, kernel density plot, and boxplot</h3>
<ul>
<li>2 numeric variables and 1 categorical variable (3 graphs each)</li>
</ul>
<section id="final-g3-portuguese-scores-numeric-vs.-study-time-categorical" class="level4">
<h4 class="anchored" data-anchor-id="final-g3-portuguese-scores-numeric-vs.-study-time-categorical">Final (G3) Portuguese Scores (numeric) vs.&nbsp;Study Time (categorical)</h4>
<p><strong>Histogram</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined, <span class="fu">aes</span>(<span class="at">x =</span> G3_por))</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> studytimeF), <span class="at">bins =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final (G3) Portuguese Scores by Study Time"</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Final Score (Portuguese)"</span>, <span class="at">y =</span> <span class="st">"Number of Students"</span>) <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I can kind of see that the centers of distributions of final scores for most of the study groups is around 12-13, and the group that studied &gt;10 hours has a lower median.</p>
<p><strong>Kernel density plot</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">fill =</span> studytimeF), <span class="at">kernel =</span> <span class="st">"gaussian"</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final (G3) Portuguese Scores by Study Time"</span>) <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Final Score (Portuguese)"</span>, <span class="at">y =</span> <span class="st">"Proportion of Students"</span>) <span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Viewing this data as a density plot makes it clearer that longer study times didn’t appear to benefit those students in terms of their final scores in Portuguese.</p>
<p>Boxplot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> studytimeF, <span class="at">y =</span> G3_por, <span class="at">fill =</span> studytimeF)) <span class="sc">+</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final (G3) Portuguese Scores by Study Time"</span>) <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Study Time"</span>, <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>) <span class="sc">+</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here it is even more evident that median scores improved with longer study time, until the students exceeded 10 hours. After that, the median score dropped, and the relative height of the box indicated more variation in scores. This suggests students who studied longer than 10 hours may have comprehension deficits that are not being adequately resolved by their chosen method of studying.</p>
</section>
<section id="final-g3-math-scores-numeric-vs.-home-address-categorical" class="level4">
<h4 class="anchored" data-anchor-id="final-g3-math-scores-numeric-vs.-home-address-categorical">Final (G3) Math Scores (numeric) vs.&nbsp;Home Address (categorical)</h4>
<p><strong>Histogram</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> G3_mat, <span class="at">fill =</span> addressF), <span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final (G3) Math Scores vs Home Address"</span>) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Final Score (Math)"</span>, <span class="at">y =</span> <span class="st">"Number of Students"</span>) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Home Address"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both urban and rural student groups show around 10 as the score with the highest relative frequency.</p>
<p><strong>Kernel density plot</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> G3_mat, <span class="at">fill =</span> addressF), </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">kernel =</span> <span class="st">"gaussian"</span>, </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final (G3) Math Scores vs Home Address"</span>) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Final Score (Math)"</span>, <span class="at">y =</span> <span class="st">"Proportion of Students"</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Home Address"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The density plot shows that the left side of the distributions are similar in shape, but that the urban students had potentially a bimodal distribution.</p>
<p><strong>Boxplot</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> addressF, <span class="at">y =</span> G3_mat, <span class="at">fill =</span> addressF)) <span class="sc">+</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Final (G3) Math Scores vs Home Address"</span>) <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Home Address"</span>, <span class="at">y =</span> <span class="st">"Final Score (Math)"</span>) <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="st">"Home Address"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Even though the median scores between the two groups is similar, the urban group had a larger interquartile range.</p>
</section>
</section>
<section id="scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots">Scatterplots</h3>
<section id="final-vs-first-period-portuguese-scores-by-study-time" class="level4">
<h4 class="anchored" data-anchor-id="final-vs-first-period-portuguese-scores-by-study-time">Final vs First Period Portuguese Scores, by study time</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined,</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> G1_por, <span class="at">y =</span> G3_por, <span class="at">color =</span> studytimeF))</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Final (G3) Portuguese Scores vs First Period Grade </span><span class="sc">\n</span><span class="st"> by Study Time"</span>,</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"First Period Score (Portuguese)"</span>, </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>,</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlation between first period and final Portuguese scores can be seen, but no discernible pattern in the study time jumps out.</p>
</section>
<section id="final-math-scores-vs-final-portuguese-scores-by-study-time" class="level4">
<h4 class="anchored" data-anchor-id="final-math-scores-vs-final-portuguese-scores-by-study-time">Final Math Scores vs Final Portuguese Scores, by study time</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined,</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> G3_mat, <span class="at">y =</span> G3_por, <span class="at">color =</span> studytimeF))</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Final (G3) Portuguese Scores vs Final (G3) Math Scores </span><span class="sc">\n</span><span class="st"> by Study Time"</span>,</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Final Score (Math)"</span>, </span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>,</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Study Time"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Again, there is correlation between final Math scores and final Portuguese scores, but I can’t really draw any meaningful relationship between these scores and study time.</p>
</section>
<section id="final-vs-first-period-portuguese-scores-by-study-time-facet-by-home-address" class="level4">
<h4 class="anchored" data-anchor-id="final-vs-first-period-portuguese-scores-by-study-time-facet-by-home-address">Final vs First Period Portuguese Scores, by study time, facet by Home Address</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined,</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> G1_por, <span class="at">y =</span> G3_por, <span class="at">color =</span> studytimeF))</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Final (G3) Portuguese Scores vs First Period Grade </span><span class="sc">\n</span><span class="st"> by Study Time"</span>,</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"First Period Score (Portuguese)"</span>, </span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>,</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Study Time"</span>) <span class="sc">+</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> addressF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Can see more variation among final and first period scores or urban students compared to rural ones.</p>
</section>
<section id="final-math-scores-vs-final-portuguese-scores-by-study-time-facet-by-home-address" class="level4">
<h4 class="anchored" data-anchor-id="final-math-scores-vs-final-portuguese-scores-by-study-time-facet-by-home-address">Final Math Scores vs Final Portuguese Scores, by study time, facet by home address</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> G3_mat, <span class="at">y =</span> G3_por, <span class="at">color =</span> studytimeF))</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Final (G3) Portuguese Scores vs Final (G3) Math Scores </span><span class="sc">\n</span><span class="st"> by Study Time"</span>,</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Final Score (Math)"</span>, </span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>,</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Study Time"</span>) <span class="sc">+</span></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> addressF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Final scores in Math vs.&nbsp;Portuguese for the rural group looks less correlated than the other combinations shown in scatterplots so far.</p>
</section>
<section id="final-vs-first-period-portuguese-scores-by-study-time-facet-by-home-address-and-family-support" class="level4">
<h4 class="anchored" data-anchor-id="final-vs-first-period-portuguese-scores-by-study-time-facet-by-home-address-and-family-support">Final vs First Period Portuguese Scores, by study time, facet by Home Address and family support</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined,</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> G1_por, <span class="at">y =</span> G3_por, <span class="at">color =</span> studytimeF))</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Final (G3) Portuguese Scores vs First Period Grade </span><span class="sc">\n</span><span class="st"> by Study Time"</span>,</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"First Period Score (Portuguese)"</span>, </span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>,</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Study Time"</span>) <span class="sc">+</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(famsupF <span class="sc">~</span> addressF, <span class="at">labeller =</span> label_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I think in this facet grid, we’re starting to see some correlation to first period and final Portuguese scores relative to family support and home address. In the bottom-right facet, it looks like there may be greater gain on final scores vs first period for rural students with family support who spent 2-5 hours studying compared to the same group who only spent &lt;2 hours studying.</p>
</section>
<section id="final-math-scores-vs-final-portuguese-scores-by-study-time-facet-by-home-address-and-family-support" class="level4">
<h4 class="anchored" data-anchor-id="final-math-scores-vs-final-portuguese-scores-by-study-time-facet-by-home-address-and-family-support">Final Math Scores vs Final Portuguese Scores, by study time, facet by home address and family support</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> student_combined,</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> G3_mat, <span class="at">y =</span> G3_por, <span class="at">color =</span> studytimeF))</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Final (G3) Portuguese Scores vs Final (G3) Math Scores </span><span class="sc">\n</span><span class="st"> by Study Time"</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Final Score (Math)"</span>, </span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final Score (Portuguese)"</span>,</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Study Time"</span>) <span class="sc">+</span></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(famsupF <span class="sc">~</span> addressF, <span class="at">labeller =</span> label_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW5_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now doing a similar plot, but instead comparing final math scores to final Portugues scores, there seems to be less correlation for the most part. Still see some increased benefit to studying 2-5 hours compared to &lt;2 hours for the urban group, no matter the family support status.</p>


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>